# Generated by Django 4.0.3 on 2022-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('city', models.CharField(max_length=200, verbose_name='cidade')),
                ('street', models.CharField(max_length=500, verbose_name='rua')),
                ('location_number', models.IntegerField(verbose_name='número')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='título')),
                ('poster', models.TextField(verbose_name='pôster')),
                ('description', models.TextField(verbose_name='descrição')),
                ('ratingAverage', models.FloatField(verbose_name='pontuação')),
                ('duration', models.IntegerField(verbose_name='duração')),
                ('genre', models.CharField(choices=[('Terror', 'Terror'), ('Aventura', 'Aventura'), ('Ação', 'Ação'), ('Ficção Científica', 'Ficção Científica'), ('Drama', 'Drama'), ('Comédia', 'Comédia'), ('Suspense', 'Suspense')], max_length=50, verbose_name='gênero')),
                ('ageGroup', models.CharField(choices=[('G', 'General Audiences'), ('PG', 'Parental Guidance Suggested'), ('PG-13', 'PG-13 - Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC-17', 'Adults only')], max_length=5, verbose_name='classificação indicativa')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='preço')),
                ('schedule', models.DateTimeField(verbose_name='horário')),
                ('chair', models.IntegerField(verbose_name='cadeira')),
                ('room', models.IntegerField(verbose_name='sala')),
                ('cinema', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema', verbose_name='cinema')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.movie', verbose_name='filme')),
            ],
        ),
    ]
