# Generated by Django 4.0.3 on 2022-04-04 23:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_remove_ticket_schedule_ticket_date_ticket_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='data'),
        ),
    ]
