# Generated by Django 4.0.3 on 2022-04-05 01:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(default='', validators=[django.core.validators.MaxLengthValidator(300, 'Número de caracteres máximo')])),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Certifique-se de que este valor seja maior ou igual a 1'), django.core.validators.MaxValueValidator(5, 'Certifique-se de que esse valor seja menor ou igual a 5.')])),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='cinema.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
