# Generated by Django 4.0.3 on 2022-04-02 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_remove_review_movie_remove_review_user_rating_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.AlterField(
            model_name='rating',
            name='score',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Certifique-se de que este valor seja maior ou igual a 1'), django.core.validators.MaxValueValidator(5, 'Certifique-se de que esse valor seja menor ou igual a 5.')]),
        ),
    ]
